version: '3'
services:
  api-gateway:
    build: './api-gateway'
    depends_on:
      - listings-service
      - users-service
    ports:
      - '7000:7000'
    volumes:
      - ./api-gateway:/opt/app

  listings-service:
    build: './listings-service'
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=postgres://root:password@listings-service-db/db?charset=UTF8
    ports:
      - '7100:7100'
    volumes:
      - ./listings-service:/opt/app

  listings-service-db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres:11
    ports:
      - 0.0.0.0:7200:5432

  users-service:
    build: './users-service'
    depends_on:
      - users-service-db
    environment:
      - DB_URI=postgres://root:password@users-service-db/db?charset=UTF8
    ports:
      - '7101:7101'
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres:11
    ports:
      - 0.0.0.0:7201:5432
